# Generated by Django 5.1.2 on 2024-10-14 12:41

import habit.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(default=1, verbose_name="Периодичность"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                default=habit.models.get_current_time, verbose_name="Время"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_to_complete",
            field=models.PositiveIntegerField(
                default=120, verbose_name="Время на выполнение"
            ),
        ),
    ]
